# memo
# -l stands for library, -lqueues means to compile with a library of name starts "queues"
0-backtracking_array:
	gcc -o 0-backtracking_array -Wall -Wextra -Werror -pedantic 0-main.c 0-backtracking_array.c -lqueues
1-backtracking_graph:
	gcc -o 1-backtracking_graph -Wall -Wextra -Werror -pedantic 1-main.c 1-backtracking_graph.c -lqueues -lgraphs
2-dijkstra_graph:
	gcc -o 2-dijkstra_graph -Wall -Wextra -Werror -pedantic 2-main.c 2-dijkstra_graph.c -lqueues -lgraphs
2-dijkstra_graph_1: # to show weakness of this algo
	gcc -o 2-dijkstra_graph_1 -Wall -Wextra -Werror -pedantic 2-main_1.c 2-dijkstra_graph.c -lqueues -lgraphs
