# memo
# -l stands for library, -lqueues means to compile with a library of name starts "queues"
0-backtracking_array:
	gcc -o 0-backtracking_array -Wall -Wextra -Werror -pedantic 0-main.c 0-backtracking_array.c -lqueues
